# Generated by Django 4.0.3 on 2022-04-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='converted',
            field=models.ImageField(blank=True, null=True, upload_to='media/converted_img'),
        ),
    ]
