# Generated by Django 4.0.3 on 2022-04-02 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_converter', '0002_image_converted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(upload_to='media/upload_img', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'ico'])]),
        ),
    ]
