# Generated by Django 4.0.3 on 2022-04-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_converter', '0003_alter_image_options_alter_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='converted',
            field=models.ImageField(null=True, upload_to='media/converted_img'),
        ),
    ]
